apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: opcua-simulator-address-space
    files:
      - opcua-address-space.yaml
