[pytest]
testpaths = libs services tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
filterwarnings =
    error
    ignore::DeprecationWarning:asyncua.*
