apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [eirvah-edge]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_eirvah_uniza_scrape]
            action: keep
            regex: "true"
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_eirvah_uniza_scrape_port]
            separator: ":"
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: app
      - job_name: rabbitmq
        static_configs:
          - targets: ["rabbitmq.eirvah-edge.svc.cluster.local:15692"]
      - job_name: nats
        static_configs:
          - targets: ["nats.eirvah-edge.svc.cluster.local:8222"]
