apiVersion: v1
kind: Service
metadata:
  name: data-converter
  labels: { app.kubernetes.io/name: data-converter }
spec:
  selector: { app.kubernetes.io/name: data-converter }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
