apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eirvah-edge
resources:
  - ../../base
patches:
  - path: actuation-control-orchestrator-patch.yaml
    target:
      kind: Deployment
      name: actuation-control-orchestrator
