apiVersion: v1
kind: Service
metadata:
  name: opcua-data-subscriber
  labels: { app.kubernetes.io/name: opcua-data-subscriber }
spec:
  selector: { app.kubernetes.io/name: opcua-data-subscriber }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
