apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: s7-data-subscriber-config
    files:
      - s7-unit-map.yaml
