apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eirvah-edge
resources:
  - namespace.yaml
  - nats
  - mosquitto
  - rabbitmq
  - prometheus
  - grafana
  - opcua-simulator
  - opcua-data-subscriber
  - data-converter
  - uns-auto-contextualizer
  - mqtt-uns-publisher
  - uns-contextualizer-orchestrator
labels:
  - includeSelectors: true
    pairs:
      eirvah.uniza/component: edge
