apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: modbus-data-subscriber-config
    files:
      - modbus-register-map.yaml
