apiVersion: v1
kind: Service
metadata:
  name: s7-simulator
  labels: { app.kubernetes.io/name: s7-simulator }
spec:
  selector: { app.kubernetes.io/name: s7-simulator }
  ports:
    - { name: s7, port: 102, targetPort: 102 }
    - { name: http, port: 8080, targetPort: 8080 }
